Add Header Block implementation
HubSpot/slack-client pull request #193
Opened 2020-09-14 20:31 UTC by richardxu100

Closes #190 

I modeled this off of `SectionIF.java` and the Header API described [here](https://api.slack.com/reference/block-kit/blocks#header). I'm very new to java, so any comments or suggestions would be very appreciated.

2020-09-14 20:36 UTC, szabowexler requested changes

2020-09-14 20:36 UTC, szabowexler commented on slack-base/src/main/java/com/hubspot/slack/client/models/blocks/HeaderIF.java
> +    return null;
Given that your precondition check indicates the header can't have a null text block, what you want to do here is remove the entire default block, and make this just:

```java
@Value.Parameter
Text getText();
```

Then you can assume text is not null, which simplifies your check block below.

2020-09-14 20:58 UTC, richardxu100 commented
Thanks for the suggestion @szabowexler! Please let me know if there's anything else that would be helpful to add to this PR

2020-09-14 20:59 UTC, szabowexler commented
Sure! The final check here is for you to confirm that you've posted a sample message, and it worked. Once you do that, just take a quick screenshot of the result and drop it here for posterity, and we'll go ahead and merge. You won't be able to use it immediately until we cut a release, but we can try and do that sometime towards the end of this week.

2020-09-15 14:20 UTC, richardxu100 commented
> Sure! The final check here is for you to confirm that you've posted a sample message, and it worked. Once you do that, just take a quick screenshot of the result and drop it here for posterity, and we'll go ahead and merge. You won't be able to use it immediately until we cut a release, but we can try and do that sometime towards the end of this week.

<img width="426" alt="Screen Shot 2020-09-15 at 10 16 10 AM" src="https://user-images.githubusercontent.com/13954830/93222045-7c13eb00-f73c-11ea-94a6-2d25d7534acc.png">

I was able to test that the header block is working properly! I'm not sure however if my method of testing is sufficient, as I basically just copied this file into my project that is using the `slack-client`. I think a more proper way to test this library would be to somehow import my local, modified `slack-client` into my project, instead of using the global version of this library, though I'm not sure how this would be done as I'm very new to java development. Do you have any suggestions on how to test this PR more properly, or is the testing I did sufficient?

2020-10-07 17:56 UTC, merged